<b>곱연산은 스칼라연산과 백터 연산이 있다<br>
스칼라 연산은 각각의 원소로 연산됨<br>
백터연산은 내적이라 부르고 가로 세로로 연산

In [6]:
import numpy as np

In [25]:
w=np.array([[1,2,3]])
x=np.array([[1,2,3]])


In [26]:
w.shape,x.shape #앞의 뒷자리와 뒤의 앞자리가 같으면 내적가능하다

((1, 3), (1, 3))

<b>y=wx+b

In [27]:
w.T.dot(x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [20]:
y.shape,x.shape #앞의 뒷자리와 뒤의 앞자리가 같으면 내적가능하다

((3, 1), (1, 2))

In [16]:
x.dot(y)

array([[5]])

In [28]:
a1=np.array([[1,1,1],[1,1,1],[1,1,1]])
b1=np.array([1,1,1])

In [29]:
a1+b1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [30]:
a2=np.array([[1],[1],[1]])
b2=np.array([1,1,1])
a2+b2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [31]:
x=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,-1)
x.shape

(3, 3)

In [34]:
ck=x>5 #스칼라처럼 각각 비교연산한다.

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [35]:
y=np.array([1,2,3])
y

array([1, 2, 3])

In [36]:
x>y

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
y=np.array([1,2])
y

array([1, 2])

In [38]:
x>y

ValueError: ignored

In [39]:
y=np.array([1]) #1차원이 아니라 단일 데이터로 계산된다. 단일 데이터는 다른 형태랑 연산이 됨
y

array([1])

In [40]:
x>y

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
data=x>y
np.all(x>y)

False

<b>Q3 난수생성(1~100)이요 100명 학생 점수 만들고 조건에 맞게 출력<br>
1. 100명 평균 50점 이상이면 전원통과<br>
2. 100명 모두가 50점 이상이면 학년1등반 출력<br>
3. 1명이라도 100점이 있다면 전교1등이 있는 반 출력

In [45]:
np.random.randint(0,101,10)

array([92, 38, 50, 76, 78, 79, 64, 73, 35, 77])

In [46]:
import numpy as np
x=np.random.randint(10,101,100)
if np.mean(x)>=50:
  print("전원통과")
if np.all(x>=50):
  print("학년 1등")
if np.any(x==100):
  print("전교1등이 있는 반")

전원통과


In [51]:
x=np.array([1,2,3,4,5])
np.where(x==3)

(array([2]),)

In [52]:
x=np.array([1,2,3,4,5])
np.where(x==3,1,2)

array([2, 2, 1, 2, 2])

In [56]:
x=np.array([2,1,5,4,3])
x

array([2, 1, 5, 4, 3])

In [57]:
np.argsort(x)

array([1, 0, 4, 3, 2])

In [59]:
np.argmax(x)

2

In [60]:
np.argmin(x)

1

In [63]:
x=np.array([2,1,5,4,3])
x

array([2, 1, 5, 4, 3])

In [64]:
np.argsort(x)

array([1, 0, 4, 3, 2])

In [68]:
l=np.array([1,2,3,4,5,6])
#l[0,2,4,3,1] #차원으로 받아들인다
l[np.array([0,2,4,3,1])] #불린 데이터로 받아들인다
#l[np.array([True,False])] #갯수를 맞춰야한다
l[np.array([True,False,True,False,True,True])]

array([1, 3, 5, 6])